name: validate

on:
  pull_request:
  push:
    branches:
      - main

jobs:
  checks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v22

      - name: Run repository checks
        run: nix shell nixpkgs#yq nixpkgs#ripgrep -c ./tooling/run-checks.sh
